kakeibo/urls.py
from django.urls import path

from . import views

app_name = 'kakeibo'

urlpatterns = [
    path('kakeibo_list/', views.KakeiboListView.as_view(), name='kakeibo_list'),
    path('kakeibo_create/', views.KakeiboCreateView.as_view(), name='kakeibo_create'),
    path('create_done/', views.create_done, name='create_done'),
    path('update/<int:pk>/', views.KakeiboUpdateView.as_view(), name='kakeibo_update'),
    path('update_done/', views.update_done, name='update_done'),
    path('delete/<int:pk>/', views.KakeiboDeleteView.as_view(), name='kakeibo_delete'),
    path('delete_done/', views.delete_done, name='delete_done'),
    path('circle/', views.show_circle_grahp, name='kakeibo_circle'),
    ]

tutorial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('kakeibo/', include('kakeibo.urls')),
]

kakeibo/models.py
from django.db import models
from datetime import datetime
# Create your models here.

class Category(models.Model):   
   class Meta:
       #テーブル名の指定
       db_table ="category"
       verbose_name ="カテゴリ"         #追加
       verbose_name_plural ="カテゴリ"  #追加

   #カラム名の定義
   category_name = models.CharField(max_length=255,unique=True)

   def __str__(self):
       return self.category_name

class Kakeibo(models.Model):
   class Meta:
       #テーブル名
       db_table ="kakeibo"
       verbose_name ="家計簿"           #追加
       verbose_name_plural ="家計簿"    #追加

   #カラムの定義
   date = models.DateField(verbose_name="日付",default=datetime.now)
   category = models.ForeignKey(Category, on_delete = models.PROTECT, verbose_name="カテゴリ")
   money = models.IntegerField(verbose_name="金額", help_text="単位は日本円")
   memo = models.CharField(verbose_name="メモ", max_length=500)

   def __str__(self):
       return self.memo

kakeibo/forms.py
from django import forms
from .models import Kakeibo

class KakeiboForm(forms.ModelForm):
   """
   新規データ登録画面用のフォーム定義
   """
   class Meta:
       model = Kakeibo
       fields =['date', 'category', 'money', 'memo']

kakeibo/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from .models import Category, Kakeibo

from . forms import KakeiboForm  #forms.pyからKakeiboFormをインポート
from django.urls import reverse_lazy
from django.db import models

#一覧表示用のDjango標準ビュー(ListView)を承継して一覧表示用のクラスを定義
class KakeiboListView(ListView):
   #利用するモデルを指定
   model = Kakeibo
   #データを渡すテンプレートファイルを指定
   template_name = 'kakeibo/kakeibo_list.html'

   #家計簿テーブルの全データを取得するメソッドを定義
   def queryset(self):
       return Kakeibo.objects.all()

class KakeiboCreateView(CreateView):

    #利用するモデルを指定
    model = Kakeibo
    #利用するフォームクラス名を指定
    form_class = KakeiboForm
    #登録処理が正常終了した場合の遷移先を指定
    success_url = reverse_lazy('kakeibo:create_done')

def create_done(request):
   #登録処理が正常終了した場合に呼ばれるテンプレートを指定
   return render(request, 'kakeibo/create_done.html')

class KakeiboUpdateView(UpdateView):
   #利用するモデルを指定
   model = Kakeibo
   #利用するフォームクラス名を指定
   form_class = KakeiboForm
   #登録処理が正常終了した場合の遷移先を指定
   success_url = reverse_lazy('kakeibo:update_done')

def update_done(request):
    #更新処理が正常終了した場合に呼ばれるテンプレートを指定
    return render(request, 'kakeibo/update_done.html')

class KakeiboDeleteView(DeleteView):

    #利用するモデルを指定
    model = Kakeibo
    #削除処理が正常終了した場合の遷移先を指定
    success_url = reverse_lazy('kakeibo:delete_done')

def delete_done(request):

    return render(request, 'kakeibo/delete_done.html')

def show_circle_grahp(request):

   #全データ取得
   kakeibo_data = Kakeibo.objects.all()

   #すべての金額の合計を求める
   total = 0
   for item in  kakeibo_data:
    total += item.money

   #カテゴリ毎の合計金額を求める
    #まずはカテゴリ名のリストデータを生成する。
    category_list =[]
    #全カテゴリ名をテーブルから取得する。
    category_data = Category.objects.all()
    #ループ処理でカテゴリ名のリストを作成する。
    for item in category_data:
        category_list.append(item.category_name)

    #つづいてカテゴリ毎の合計金額を求める
    category_dict = {}  #カテゴリ毎の割合を格納する辞書型を定義
    for i,item in enumerate(category_list):
        category_total = Kakeibo.objects.filter(category__category_name=category_list[i])\
        .aggregate(sum=models.Sum('money'))['sum']
        if category_total != None:
            ratio = int((category_total / total) *100)
            category_dict[item] = ratio
        else:
            ratio = 0
            category_dict[item] = ratio

    return render(request, 'kakeibo/kakeibo_circle.html',{
        'category_dict': category_dict,
         } )

kakeibo/templates/kakeibo/base.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {# Bootstrap4を使う #}
  <!-- linkタグでbootstrapのcssファイルを読み込む -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
  <!-- linkタグでDataTableのcssファイルを読み込む -->
  <link rel="stylesheet" href="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.css"/> 

  <!-- タイトルの設定-->
  <title>Tutorial</title>

<body>

  {% block content %}

   <!-- block content ～ endblockの間に子テンプレートの内容が差し込まれる -->

  {% endblock %}

  <!-- bootstrapのjavascrit読み込み-->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
  <!-- DataTablesのjavascrit読み込み-->
  <script src="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.js"></script>
  <!-- chart.jsの読み込み -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>

  <!-- DataTableの定義-->
  <script>
  jQuery(function($){
    // デフォルトの設定を変更
    $.extend( $.fn.dataTable.defaults, {
        language: {
            url: "http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Japanese.json"
            }
            });
    $("#kakeibo_list").DataTable({
        "searching": true,     //検索機能
        "paging":   true,      //ページング機能
        "ordering": true,      //ソート機能
        "lengthChange": true,  //件数切り替え機能

        }).columns.adjust().draw();
        });
  </script>

  <!-- 描画する円グラフの定義-->
  <script>
    var ctx = document.getElementById('CircleChart').getContext('2d');
    var data = [
                [
                 {% for key, value in category_dict.items%}
                  '{{key}}',
                 {% endfor %}
                ],

                [
                {% for key, value in category_dict.items%}
                   {{value}},
                {% endfor %}
                ]]

    var myChart = new Chart(ctx, {
      type: 'pie',

      data: {
        labels: data[0],
        datasets: [{
          data:  data[1],
          backgroundColor: ["rgba(255,241,15,0.8)","rgba(54,164,235,0.8)",
          "rgba(0,255,65,0.8)","rgba(214,216,165,0.8)","rgba(255,94,25,0.8)",
          "rgba(84,77,203,0.8)","rgba(140,140,140,0.8)","rgba(171,255,127,0.8)",
          "rgba(50,204,18,0.8)","rgba(234,210,173,0.8)"],
        },
      ] }
    });
</script>

</body>
</html>

kakeibo/templates/kakeibo/create_done.html
{% extends 'kakeibo/base.html' %}
{% block content %}

 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'kakeibo:kakeibo_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">家計簿アプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <i class="fa fa-server"></i> <b>家計簿アプリ</b></div>
       <div class="card-body">
<div class="alert alert-info" role="alert">データ登録が正常終了しました。</div>
{% endblock content %}

kakeibo/templates/kakeibo/delete_done.html
{% extends 'kakeibo/base.html' %}
{% block content %}

 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'kakeibo:kakeibo_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">家計簿アプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <i class="fa fa-server"></i> <b>家計簿アプリ</b></div>
       <div class="card-body">
<div class="alert alert-info" role="alert">データ削除処理が正常終了しました。</div>
{% endblock content %}

kakeibo/templates/kakeibo/kakeibo_circle.html
<!-- 親テンプレートを読み込む-->
{% extends 'kakeibo/base.html' %}
{% block content %}
 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- パンくずリストの設定-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'kakeibo:kakeibo_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">カテゴリ毎の合計金額割合</li>
     </ol>
     <!--ページタイトル-->
     <div class="card mb-3">
       <div class="card-header">
          <h3><b>家計簿アプリ（カテゴリ毎の合計金額割合）</b></h3></div>
       <div class="card-body">
         <!-- 円グラフの描画-->
         <div class="chart_container">
             <canvas id='CircleChart' style="position: relative; height:1vh; width:1vw"></canvas>
           </div>
       </div>
      </div>
   </div>
  </div>
   <style>
      .chart_container {
          width: 640px;
          margin: auto;
        }
  </style>
{% endblock content %}

kakeibo/templates/kakeibo/kakeibo_confirm_delete.html
{% extends 'kakeibo/base.html' %}
{% block content %}
 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'kakeibo:kakeibo_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">家計簿アプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <h3>データ削除</h3></div>
       </div>
       <div class="content-wrapper">
         <div class="container-fluid">
           <p>{{ object }} のデータを削除していいですか?</p>

           <form method="post">
             <button class="btn btn-danger">削除する</button>
             {% csrf_token %}
           </form>
         </div>
       </div>
   </div>
 </div>
{% endblock %}

kakeibo/templates/kakeibo/kakeibo_form.html
{% extends 'kakeibo/base.html' %}
{% load bootstrap %}
{% block content %}

 <!-- formタグを設定し、postメソッドを指定 -->
 <form method="post">
   <div class="container">
     <div class="row">
       <div class="col-12">
         <div class="content-wrapper">
           <div class="container-fluid">
             <!-- Breadcrumbs-->
             <ol class="breadcrumb">
               <li class="breadcrumb-item">
                 <a href="{% url 'kakeibo:kakeibo_list' %}">TOP</a>
               </li>
               <li class="breadcrumb-item active">家計簿アプリ</li>
               <li class="breadcrumb-item active">データ登録</li>
             </ol>
             <!-- Example DataTables Card-->
             <div class="card mb-3">
               <div class="card-header">
                 <i class="fa fa-server"></i> <h3>データ登録画面</h3></div>
               <div class="card-body">          {{ form|bootstrap }}
       </div>
     </div>
     <div class="row">
       <div class="col-12">
         <!-- データ保存ボタンを設定 -->
         <button class="btn btn-primary">保存</button>
       </div>
     </div>
   </div>
   {% csrf_token %}
         <!-- formタグを閉じる -->
 </form>
{% endblock %}

kakeibo/templates/kakeibo/kakeibo_list.html
<!-- 親テンプレートを読み込む-->
{% extends 'kakeibo/base.html' %}
{% block content %}
 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- パンくずリストの設定-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'kakeibo:kakeibo_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">一覧表示</li>
       <li class="breadcrumb-item">
        <a href="{% url 'kakeibo:kakeibo_circle' %}">円グラフ</a>
       </li>
     </ol>
     <!--ページタイトル-->
     <div class="card mb-3">
       <div class="card-header">
         <h3><b>家計簿アプリ</b></h3></div>
       <div class="card-body"> 
         <!-- テーブル表の定義 -->
         <div class="table-responsive">
         <table id=kakeibo_list width="100%" class="table table-striped table-bordered table-hover">
           　<!-- 表の列の定義-->
             <thead>
               <tr>
                 <th class="text-center">日付</th>
                 <th class="text-center">カテゴリ</th>
                 <th class="text-center">金額</th>
                 <th class="text-center">メモ</th>
                 <th class="text-center">更新・削除</th> <!--追加-->
               </tr>
             </thead>
           　<!-- ここまでが表の列の定義-->
           　<!-- 表のデータ部分の表示-->
             <tbody>
               {% for item in object_list %}
                 <tr class="odd gradeX text-center">
                   <td class="text-center" width="100">{{ item.date}}</td>
                   <td class="text-center" width="100">{{ item.category }}</td>
                   <td class="text-center" width="140">{{ item.money }}</td>
                   <td class="text-center" width="140">{{ item.memo }}</td>
                   <td class="text-center" width="140">
                    <a class="btn btn-primary" href="{% url 'kakeibo:kakeibo_update' item.pk %}">更新ページ</a>
                    <a class="btn btn-danger" href="{% url 'kakeibo:kakeibo_delete' item.pk %}">削除ページ</a>
                   </td> <!--追加-->
                 </tr>
             {% endfor %}
             </tbody>
           　<!-- ここまでが表のデータ部分の表示-->
           </table>
           <!-- ここまでがテーブル表の定義 -->
        　<a class="btn btn-primary" href="{% url 'kakeibo:kakeibo_create' %}">新規作成</a>
       </div>
      </div>
      </div>
   </div>
  </div>
{% endblock content %}

kakeibo/templates/kakeibo/update_done.html
{% extends 'kakeibo/base.html' %}
{% block content %}

 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'kakeibo:kakeibo_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">家計簿アプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <i class="fa fa-server"></i> <b>家計簿アプリ</b></div>
       <div class="card-body">
<div class="alert alert-info" role="alert">データ更新処理が正常終了しました。</div>
{% endblock content %}